package my.maleva.api.module.fleet.entity;

import java.time.LocalDateTime;

/**
 * The shape shared by the truck pass documents: {@link LeviEntry} and
 * {@link AutoPassEntry}.
 *
 * The two tables carry the same twenty-one columns, and their legacy .NET
 * controllers and services were byte-identical apart from the {@code LE} / {@code AP}
 * number prefix. This interface is what lets one service implementation serve
 * both instead of the pair of near-copies the legacy code kept.
 *
 * Every method here is already generated by Lombok on both entities, so
 * implementing it adds no code to either.
 */
public interface PassEntry {

    Integer getId();

    Integer getCompanyRefId();

    Integer getCNumber();

    String getCNumberDisplay();

    LocalDateTime getSaleDate();

    Integer getTruckRefid();

    Integer getDriverRefId();

    Integer getRtiRefId();

    Integer getEmployeeRefId();

    /** One of {@code IN} / {@code OUT}. */
    String getEnterLink();

    /** One of {@code 1ST LINK} / {@code 2ND LINK}. */
    String getExitLink();

    Float getAmount();

    String getRemarks();

    String getFilePath();

    LocalDateTime getCreatedDate();

    LocalDateTime getModifiedDate();

    // Setters for the soft delete, which loads the entry and updates it as a
    // managed entity rather than firing a bulk UPDATE. See
    // AbstractPassEntryService.delete for why the bulk form cannot work here.

    void setActive(Integer active);

    void setModifiedDate(LocalDateTime modifiedDate);

    void setModifiedBy(String modifiedBy);
}
