package my.maleva.api.module.ceodashboard.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "Data Transfer Object representing a Top Customer in the CEO Dashboard")
public class TopCustomerResponseDto {

    @Schema(description = "The calculated rank of the customer (1 to 20)", example = "1")
    private Integer rank;

    @Schema(description = "The unique Customer Code", example = "CUST-001")
    private String customerCode;

    @Schema(description = "The Customer Name", example = "AMS MARINE SDN BHD")
    private String customerName;
    
    // Revenue & Profit
    @Schema(description = "Total revenue generated by this customer in the selected time period", example = "1294254.60")
    private BigDecimal totalRevenue;

    @Schema(description = "Total volume (e.g. TEU or tonnage) handled for this customer", example = "500")
    private Integer totalVolume;

    @Schema(description = "Total Gross Margin (Revenue - Cost)", example = "450000.00")
    private BigDecimal grossMargin;

    @Schema(description = "Margin percentage calculated as (Gross Margin / Total Revenue) * 100", example = "34.77")
    private BigDecimal marginPercentage;
    
    // Job Metrics
    @Schema(description = "Total number of jobs/shipments completed for this customer", example = "250")
    private Integer totalJobs;

    @Schema(description = "Average revenue per shipment", example = "5177.01")
    private BigDecimal avgRevenuePerShipment;
    
    // Complaints & Service
    @Schema(description = "Total lifetime complaints registered by this customer", example = "2")
    private Integer complaintCount;

    @Schema(description = "Number of currently unresolved complaints", example = "0")
    private Integer openComplaints;
    
    // Dates
    @Schema(description = "Date and time of the last shipment for this customer", example = "2026-08-01T10:00:00")
    private LocalDateTime lastShipmentDate;

    @Schema(description = "Date and time of the last invoice issued", example = "2026-08-02T14:30:00")
    private LocalDateTime lastInvoiceDate;

    @Schema(description = "Date and time of the last payment received", example = "2026-07-28T09:15:00")
    private LocalDateTime lastPaymentDate;

    @Schema(description = "Number of days elapsed since the last shipment", example = "4")
    private Integer daysSinceLastShipment;
    
    // Financial Health
    @Schema(description = "Total outstanding (unpaid) amount", example = "150000.00")
    private BigDecimal outstandingAmount;

    @Schema(description = "Total credit limit allocated to this customer", example = "500000.00")
    private BigDecimal creditLimit;

    @Schema(description = "Percentage of credit currently utilized", example = "30.00")
    private BigDecimal creditUtilizationPercentage;
    
    // Risk & Growth
    @Schema(description = "Growth percentage compared to the previous equivalent period", example = "12.5")
    private BigDecimal growthPercentage;

    @Schema(description = "Indicates if a competitor is actively targeting this account", example = "No")
    private String competitorRisk; 

    @Schema(description = "Name of the primary competitor (if any)", example = "N/A")
    private String competitorName;

    @Schema(description = "The Sales Person managing this account", example = "John Doe")
    private String salesPerson;
    
    // Overall Status
    @Schema(description = "The health status of the customer (e.g., Active, At Risk, Critical)", example = "Active")
    private String customerStatus; 
}
