package my.maleva.api.module.purchase.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import jakarta.validation.constraints.*;
import java.time.LocalDateTime;

/**
 * PurchaseDetailsDto - Data Transfer Object for PurchaseDetails entity
 * Represents individual line items within a purchase order
 *
 * Maps to: PurchaseDetails entity
 * Table: PurchaseDetails
 *
 * Fields synchronized with PurchaseDetails entity:
 * - Id: Primary Key
 * - PurchaseMasterRefId: Foreign Key to PurchaseMaster (required)
 * - ProductMasterRefId: Foreign Key to ProductMaster (required)
 * - MRP, PurchaseRate, ItemQty, Discount fields
 * - Tax fields (TaxPercent, TaxAmount)
 * - Amount calculations (SalesRate, NetSalesRate, Amount)
 * - Audit fields (CreatedDate, ModifiedDate)
 * - Remarks and product information
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PurchaseDetailsDto {

    /**
     * Primary Key - Line item ID
     * Auto-generated by database
     */
    private Integer id;

    /**
     * Foreign Key to PurchaseMaster table
     * Links this detail line to its parent purchase order
     * Required field - cannot be null
     */
    @NotNull(message = "Purchase Master Reference ID is required")
    private Integer purchaseMasterRefId;

    /**
     * Foreign Key to ProductMaster table
     * CRITICAL: Must be > 0 (not 0, as 0 is invalid product ID)
     * Cannot be null - must reference valid product
     * Required field
     */
    @NotNull(message = "Product Master Reference ID is required")
    private Integer productMasterRefId;

    /**
     * Maximum Retail Price of the product
     * Double precision for decimal values
     */
    private Double mrp;

    /**
     * Purchase Rate - Cost at which item was purchased
     * Double precision for decimal values
     */
    private Double purchaseRate;

    /**
     * Item Quantity - Number of items ordered
     * VALIDATION: Must be > 0 (CHECK constraint in database)
     * Double to support fractional units (e.g., 2.5 kg, 3.75 m)
     */
    private Double itemQty;

    /**
     * Discount Percentage - Discount rate applied to this line
     * Range: 0-100 percent
     * Double precision for decimal percentages (e.g., 10.5%)
     */
    private Double discPer;

    /**
     * Discount Amount - Calculated final discount in currency
     * Derived from: ItemQty × SalesRate × (DiscPer / 100)
     * Double precision for decimal currency values
     */
    private Double discAmount;

    /**
     * Landing Cost - Final cost including freight, tax, etc.
     * Total cost to company for this line item
     * Double precision for decimal values
     */
    private Double landingCost;

    /**
     * Tax Percentage - Tax rate applied to this line
     * Range: 0-100 percent (e.g., 5%, 18%)
     * Double precision for decimal percentages
     */
    private Double taxPercent;

    /**
     * Tax Amount - Calculated tax in currency
     * Derived from: Amount × (TaxPercent / 100)
     * Double precision for decimal currency values
     */
    private Double taxAmount;

    /**
     * Sales Rate - Selling price per unit
     * Used for revenue calculation
     * Double precision for decimal values
     */
    private Double salesRate;

    /**
     * Net Sales Rate - Rate after discount
     * Derived from: SalesRate - (SalesRate × DiscPer / 100)
     * Double precision for decimal values
     */
    private Double netSalesRate;

    /**
     * Total Amount - Final line item amount with tax and discount
     * Calculated as: (ItemQty × SalesRate) - DiscAmount + TaxAmount
     * VALIDATION: Must be > 0 (CHECK constraint in database)
     * Double precision for decimal currency values
     */
    private Double amount;

    /**
     * Date and time when this detail line was created
     * Auto-set by stored procedure/application to GETDATE()
     * Used for audit trail
     */
    private LocalDateTime createdDate;

    /**
     * Date and time when this detail line was last modified
     * Updated whenever record is changed
     * Used for audit trail and concurrency control
     */
    private LocalDateTime modifiedDate;

    /**
     * Remarks/Notes for this line item
     * Free text field (max 300 characters)
     * Can contain special instructions or notes about this line
     */
    private String remarksD;

    /**
     * Currency Value - Exchange rate if dealing with foreign currency
     * Used for multi-currency support
     * Double precision for decimal exchange rates
     */
    private Double currencyValue;

    /**
     * Actual Amount - Amount in original/foreign currency
     * Before conversion to company base currency
     * Double precision for decimal values
     */
    private Double actualAmount;

    /**
     * Product Name - Description of the product ordered
     * Denormalized from ProductMaster for display purposes
     * Max 300 characters
     * Examples: "LABOUR CHARGE", "80/90KM STICKER", "PART XYZ"
     */
    private String productName;

    /**
     * Product Code - SKU or product code
     * Denormalized from ProductMaster for identification
     * Max 300 characters
     * Examples: "MAINT-LC01", "SP-ST05", "SP-CP03"
     */
    private String productCode;
}

