USE [LiveMaleva2]
GO

/****** Object:  Table [dbo].[VESSELPLANINGDetails]    Script Date: 1/3/2026 2:10:06 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[VESSELPLANINGDetails](
	[Id] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[VESSELPLANINGMasterRefId] [int] NOT NULL,
	[SaleOrderMasterRefId] [int] NOT NULL,
	[Remarks] [varchar](300) NULL,
	[Created_Date] [datetime] NOT NULL,
	[Modified_Date] [datetime] NOT NULL,
 CONSTRAINT [PK_VESSELPLANINGDetails] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[VESSELPLANINGDetails] ADD  CONSTRAINT [DF_VESSELPLANINGDetails_Created_Date]  DEFAULT (getdate()) FOR [Created_Date]
GO

ALTER TABLE [dbo].[VESSELPLANINGDetails] ADD  CONSTRAINT [DF_VESSELPLANINGDetails_Modified_Date]  DEFAULT (getdate()) FOR [Modified_Date]
GO

ALTER TABLE [dbo].[VESSELPLANINGDetails]  WITH NOCHECK ADD  CONSTRAINT [FK_VESSELPLANINGDetails_SaleOrderMaster] FOREIGN KEY([SaleOrderMasterRefId])
REFERENCES [dbo].[SaleOrderMaster] ([Id])
GO

ALTER TABLE [dbo].[VESSELPLANINGDetails] CHECK CONSTRAINT [FK_VESSELPLANINGDetails_SaleOrderMaster]
GO

ALTER TABLE [dbo].[VESSELPLANINGDetails]  WITH NOCHECK ADD  CONSTRAINT [FK_VESSELPLANINGDetails_VESSELPLANINGMaster] FOREIGN KEY([VESSELPLANINGMasterRefId])
REFERENCES [dbo].[VESSELPLANINGMaster] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
NOT FOR REPLICATION 
GO

ALTER TABLE [dbo].[VESSELPLANINGDetails] CHECK CONSTRAINT [FK_VESSELPLANINGDetails_VESSELPLANINGMaster]
GO

